# Generated by Django 2.1 on 2018-08-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_analyse',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='articles_news',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='articles_tutorial',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
