# Generated by Django 2.1 on 2018-08-18 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20180815_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles_analyse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 12, 20, 23, 525595, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='articles_news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 12, 20, 23, 525595, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='articles_tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 18, 12, 20, 23, 525595, tzinfo=utc)),
        ),
    ]
