# Generated by Django 2.1 on 2018-08-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180818_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles_analyse',
            name='date',
        ),
        migrations.RemoveField(
            model_name='articles_tutorial',
            name='date',
        ),
    ]
