# Generated by Django 2.1 on 2018-08-18 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20180818_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles_analyse',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articles_news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articles_tutorial',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
